name: Release
on:
  push:
    tags: 
      - v*
jobs:
  release:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Deploy to host via Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude .git --exclude .github
          path: /
          remote_path: /var/www/html/staging/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: Message Slack
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
